name: Test SciUnit Across OS Versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: Ubuntu_24.04
            dockerfile: files/ubuntu24/Dockerfile
          - name: Ubuntu_22.04
            dockerfile: files/ubuntu22/Dockerfile
          - name: Ubuntu_20.04
            dockerfile: files/ubuntu20/Dockerfile
          - name: Ubuntu_18.04
            dockerfile: files/ubuntu18/Dockerfile
          # - name: Debian 12
          #   dockerfile: files/debian12/Dockerfile
          # - name: Fedora 40
          #   dockerfile: files/fedora40/Dockerfile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image for ${{ matrix.name }}
        run: |
          docker build \
            -t "sciunit-test:${{ matrix.name }}" \
            -f "${{ matrix.dockerfile }}" \
            .


      - name: Run SciUnit test for ${{ matrix.name }}
        run: |
          echo "Running SciUnit test on ${{ matrix.name }}"
          docker run --rm \
            -v ${{ github.workspace }}/files/utility/test_sciunit.sh:/test_sciunit.sh:ro \
            sciunit-test:${{ matrix.name }} \
            bash /test_sciunit.sh
